export enum SchoolPermission {
  // Dashboard
  VIEW_DASHBOARD = 'VIEW_DASHBOARD',

  // User Management
  VIEW_USERS = 'VIEW_USERS',
  CREATE_USER = 'CREATE_USER',
  EDIT_USER = 'EDIT_USER',
  DELETE_USER = 'DELETE_USER',
  APPROVE_USER = 'APPROVE_USER',
  MANAGE_USER_PERMISSIONS = 'MANAGE_USER_PERMISSIONS',
  RESET_USER_PASSWORD = 'RESET_USER_PASSWORD',
  VIEW_ACCESS_LOGS = 'VIEW_ACCESS_LOGS',

  // Staff Management
  VIEW_STAFF = 'VIEW_STAFF',
  CREATE_STAFF = 'CREATE_STAFF',
  EDIT_STAFF = 'EDIT_STAFF',
  DELETE_STAFF = 'DELETE_STAFF',

  // Class Management
  VIEW_CLASSES = 'VIEW_CLASSES',
  CREATE_CLASS = 'CREATE_CLASS',
  EDIT_CLASS = 'EDIT_CLASS',
  DELETE_CLASS = 'DELETE_CLASS',

  // Subject Management
  VIEW_SUBJECTS = 'VIEW_SUBJECTS',
  CREATE_SUBJECT = 'CREATE_SUBJECT',
  EDIT_SUBJECT = 'EDIT_SUBJECT',
  DELETE_SUBJECT = 'DELETE_SUBJECT',

  // Student Management
  VIEW_STUDENTS = 'VIEW_STUDENTS',
  CREATE_STUDENT = 'CREATE_STUDENT',
  EDIT_STUDENT = 'EDIT_STUDENT',
  DELETE_STUDENT = 'DELETE_STUDENT',

  

  // Grading
  VIEW_GRADES = 'VIEW_GRADES',
  CREATE_GRADE = 'CREATE_GRADE',
  EDIT_GRADE = 'EDIT_GRADE',
  DELETE_GRADE = 'DELETE_GRADE',

  // Performance
  VIEW_PERFORMANCE = 'VIEW_PERFORMANCE',
  GENERATE_REPORTS = 'GENERATE_REPORTS',

  // Reports
  VIEW_REPORTS = 'VIEW_REPORTS',
  EXPORT_REPORTS = 'EXPORT_REPORTS',

  // Leave Management
  VIEW_LEAVE = 'VIEW_LEAVE',
  CREATE_LEAVE = 'CREATE_LEAVE',
  EDIT_LEAVE = 'EDIT_LEAVE',
  DELETE_LEAVE = 'DELETE_LEAVE',
  APPROVE_LEAVE = 'APPROVE_LEAVE',

  // Parent Portal (Read-only access to child data)
  VIEW_OWN_CHILD = 'VIEW_OWN_CHILD',
  VIEW_CHILD_PERFORMANCE = 'VIEW_CHILD_PERFORMANCE',
  VIEW_CHILD_PATHWAY = 'VIEW_CHILD_PATHWAY',
  VIEW_CHILD_REPORTS = 'VIEW_CHILD_REPORTS',
  VIEW_CHILD_ATTENDANCE = 'VIEW_CHILD_ATTENDANCE',
  RECEIVE_NOTIFICATIONS = 'RECEIVE_NOTIFICATIONS',
  MESSAGE_TEACHER = 'MESSAGE_TEACHER',
}
